language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
before_deploy:
  - grunt build
  - cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: api
  api_key:
    secure: UhTg6D7yqtsCIPQaX1J3LcP2sWnpMff4kSCqZlwrBx+pzgrLFZci7V5sdjvGJuBEQTyIS+SKzGCKEu6eIsNaae05c8mRIuVC/OJ9O+en+PcfOafvNQn8Tizt4nkTDGxZy1HlHAOW9xUWtH45uUFjevxpYhagoOuqWOrnLotpV4ggGo08PYkrtZgqn4UfpFE8tUH5Q1RzbruvwC3eacJDfx1ZyUXu9Eaigq8Y/w/uZPjFkqXloqpVjwZiLEfX+Kr97cVZ83Opjn5TxlaEvAR228DBAEMD9TMPU6g/f5opCzQZboPdx1EKzOZ/kjHrEi8xn91j/rTyrohldPXyjp13GN8+t22Qf2xLmtZiAy7xbhJiLgDkfaQ2qcMKPNrVPuhGIuyw7zL558p1MuE8sSgldMo+EqAcRomK3ee58fVqdVdF2VE81dThd9uWNbvK+ITihBu1Yag1wOKBKHVCjJIFluvChtHdHXa9rUlZ9GN32KRDcyKz5rzC4em3L+MoOz1stMBXQ8BcZD3FGXj7nCZ61keo6neminZlD/uq6PRSAK30jYbhJ1usN4sKE8P12czQomsXsVLAIWpgyTdl/w77FfrnFTKH8gteoDQM4oaNvUEu8G/LfljtPjZCwb2eigwBp94Z/9HZ32K/vgDem/nZo8q0C/aK/C8+kcXbZrFnfwE=
  app: think-kids-certification
  on:
    repo: matteverson/think-kids-certification-program
