language: node_js
node_js:
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
after_success:
  - rvm use 2.2.0
  - bash ./travis/after_success.sh
