language: node_js
node_js:
  - '0.12'
cache:
  directories:
    - node_modules
before_script:
  - npm install -g bower grunt-cli
  - gem install sass
  - bower install
services: mongodb
before_deploy:
  - grunt build
  - cd dist
deploy:
  provider: heroku
  skip_cleanup: true
  strategy: api
  api_key:
    secure: SzDEwusSiWW0i0pQyCZMpP07+D7Al134b+x1XAoYCY5vWgGbDBFIv711aKkIXt02op0z3NIIGeDH6yEi1+ohYEU9NdAn4QQWyo0sx9eU99mB5/26Sm5p1BmBVbzg7y6CWmPFdcmF+/RYpY4C1SpfbXl8WoUUhXPw9NBy12ctS1WI7JkSwqMioOk9+SC7zmH08yS+kfkwi5RZvusD0eXwoEV2AQP3p6kHIC1g7LL+b2qopKwa4yXx1+kCkSLFUnm9JLidUMnX66XZJuO3EY7ToMgW5X2RxMxXVa4S4Ts7VB0SEKmSnYLEByTPBmrTzhtUMCxV1/Z9qOrFXoV0xnBjtrEqcLMZCyxNgaJjho6Yd/cEkhPIErCwQj3H1UTotvRzVDxF4Ykns/9zfu14WQ0shFAzkGnvDEqYg224L6jZIWth1TAs16bYVjkmpMq+jN4ZVdMaFoMghC/wc3ic8xLe+Fl3yqsUHl7NZnzMalTsOBB6OV9iWQnJQtnSikFmMgnw7GGlG9OxBGEc1oJiTyNaPiZXsaMmeH51jV7bChS97b+NUmTHLh4/KGQesGq7D+zTgIhBVnMpEoL4OoORadbaAB8pgjTegYk98n+zFR08c1S7ZD6jGZOuSho/6Ra+/w9hqwJw/iBppakbv2PZpoOiLddqojU8RTpFzaEmQIFmTcM=
  app: think-kids-certification
  on:
    repo: matteverson/think-kids-certification-program
